###
GET http://localhost:3000/accounts


###
POST http://localhost:3000/transfer
Content-Type: application/json

{
    "fromId": 1,
    "toId": 2,
    "amount": 3000
}

###
POST http://localhost:3000/consistent-transfer
Content-Type: application/json

{
  "fromId": 1,
  "toId": 2,
  "amount": 10000
}

###
POST http://localhost:3000/isolation-lost-update